-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Iphone 12', 'Mobile', 'A 24 months contract on iphone 12 with a monthly rate of 90');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Superstore', 'Grocery', 'Casual Food Restock');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Microwave', 'Appliance', 'Bestbuy promotion');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'ASUS Laptop', 'Electronics', 'Gaming laptop replacement');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Nikon D100', 'Camera', 'For studio');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Yonex ArcSaber 11 Badminton Racquet', 'Sports', 'For upcoming tournament');
-- INSERT INTO items (user_id, name, category, description) VALUES (1, 'Sony Headphone', 'Audio', 'Birthday gift for Mikhail');