-- INSERT INTO files (item_id, name, url) VALUES (1, 'iphone-11-pro-info.pdf', './uploads/1/1/iphone-11-pro-info.pdf');
-- INSERT INTO files (item_id, name, url) VALUES (2, 'receipt.jpg', './uploads/1/2/receipt.jpg');
-- INSERT INTO files (item_id, name, url) VALUES (3, 'microwave-warranty.png', './uploads/1/3/microwave-warranty.png');
-- INSERT INTO files (item_id, name, url) VALUES (4, 'Asus-Product-Guide.pdf', './uploads/1/4/Asus-Product-Guide.pdf');